# Fly.io configuration for Telegram Bot
app = "ceobuying-bot"
primary_region = "ord" # Chicago - change to your preferred region

[build]
  dockerfile = "Dockerfile.bot"

[env]
  # Public env vars (secrets go via `fly secrets set`)
  SUPPORT_EMAIL = "contact@ceobuying.com"

# VM configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Auto-restart if crashes
[processes]
  app = "node src/bot/bot.js"

# Health check (optional - bot doesn't have HTTP endpoint)
# Uncomment if you add health endpoint
# [[services]]
#   internal_port = 3000
#   protocol = "tcp"
#
#   [[services.ports]]
#     port = 80
#     handlers = ["http"]
#
#   [services.concurrency]
#     hard_limit = 25
#     soft_limit = 20
#
#   [[services.tcp_checks]]
#     grace_period = "10s"
#     interval = "30s"
#     restart_limit = 0
#     timeout = "5s"
